default: &default
  date: ["月","火","水","木","金","土","日、祝日","祝前日"]
# [["月",1], ["火",2], ["水",3], ["木",4], ["金",5], ["土",6], ["日、祝日",7], ["祝前日",8]]
development:
  <<: *default
  key2: value2.d

test:
  <<: *default
  key2: value2.t

production:
  <<: *default
  key2: value2.p
