default: &default
  date: ["月","火","水","木","金","土","日、祝日","祝前日"]
  year: 2000
  month: 1
  day: 1
  date_statuses: ["WEEKDAY","HOLIDAY"]
development:
  <<: *default
  key2: value2.d

test:
  <<: *default
  key2: value2.t

production:
  <<: *default
  key2: value2.p
